### ISSUE TITLE
Location results bug

### ISSUE THREAD

**Issue by robinpiets** [Amsterdam/Vergunningschecker#117]
### Results for `suffix` should have an exact match on `streetNumber`.

Reproduce bug: 
Postalcode: 1025ve
Streetnumber: 1

---

![image](https://user-images.githubusercontent.com/7781865/72073613-8994ed80-32f0-11ea-9ea3-e4d0399d1813.png)

**Comment by svenjens** [comment]
Might be related: 
https://github.com/Amsterdam/Vergunningschecker/pull/96
