### ISSUE TITLE
Jenkins/Browser: acceptance doesn't fetch API's sometimes

### ISSUE THREAD

**Issue by robinpiets** [Amsterdam/Vergunningschecker#133]
After deploying to acceptance and testing in the browser, the Console shows errors, like `Cross-Origin Request Blocked` from `netlify.com`.

It's hard to reproduce at this time, and maybe related to #92, but it is pretty annoying..

**Comment by robinpiets** [comment]
Possible solutions:
1. https://stackoverflow.com/questions/43635649/adding-http-headers-to-webpack-bundle-requests#43639768
2. https://github.com/Amsterdam/blackspots-frontend/blob/22a50057bcf5f1f15e39970d364583a6f28d0df8/netlify.toml
3. https://stackoverflow.com/questions/43628859/force-react-application-to-update-after-deployment

**Comment by svenjens** [comment]
fixed by #139
