### ISSUE TITLE
Chappie 1.0 English network error

### ISSUE THREAD

**Issue by robinpiets** [Amsterdam/Vergunningschecker#301]
#### @afjlambert, shall we make the error `Network error: Failed to fetch` in Dutch?

----

![image](https://user-images.githubusercontent.com/7781865/78118544-71240300-7407-11ea-8e2a-f4b18fffa16a.png)

----

**Comment by afjlambert** [comment]
@robinpiets is this still relevant after all your changes?

**Comment by robinpiets** [comment]
Nope!
