### ISSUE TITLE
State Management enhancements

### ISSUE THREAD

**Issue by robinpiets** [Amsterdam/Vergunningschecker#77]
- [ ] When returning to `LocationPage` the values of all fields are lost, needs to be saved
- [ ] When returning to `LocationPage`, and you don't change anything, continue the questionnaire instead of going to the first question

**Comment by svenjens** [comment]
Let's wait with this till we know if you can use GraphQL. Because than we might use Apollo Client

**Comment by robinpiets** [comment]
Fixed with GraphQL
